# Generated by Django 5.1.3 on 2024-11-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='experiencia_level',
            new_name='experience_level',
        ),
    ]
