# Generated by Django 5.1.3 on 2024-11-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='previous_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='wallet',
            field=models.ForeignKey(limit_choices_to={'user__is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='users.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
