# Generated by Django 5.1.3 on 2024-11-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Acción'), ('crypto', 'Criptomoneda'), ('commodity', 'Comodidad'), ('forex', 'Forex')], max_length=20),
        ),
    ]
