# Generated by Django 5.1.3 on 2024-12-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_asset_current_value_alter_asset_market_cap_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
    ]
