# Generated by Django 5.1.3 on 2024-12-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_asset_transaction_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal')], max_length=50),
        ),
    ]
