# Generated by Django 5.1.3 on 2024-12-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_transaction_status_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=50),
        ),
    ]
